---

- include_tasks: variables.yml

- include_tasks: assertions.yml

- include_tasks: "{{ ansible_os_family }}/install.yml"

- include_tasks: easy-rsa.yml

#- include_tasks: clients.yml

- include_tasks: configure.yml

- name: Upload server keys
  unarchive:
    src: "{{ export_server_file_name }}"
    dest: "{{ openvpn_keydir }}"
    mode: 0600
    owner: root
    group: root

- name: Create client config dir
  file:
    dest: "{{ openvpn_client_config_dir }}"
    state: directory
  when: openvpn_client_config_dir is defined

- name: Upload client keys
  unarchive:
    src: "{{ export_client_file_name }}"
    dest: "{{ openvpn_client_config_dir }}"
    mode: 0600
    owner: root
    group: root
    exclude:
      - "*/ca.crt"
      - "*/ta.key"
      - "*/*.ovpn"
  when: openvpn_client_config_dir is defined

- include_tasks: "{{ ansible_os_family }}/setup-bridge.yml"

- include: firewall.yml
  when: openvpn_route_traffic | bool

- include_tasks: service.yml
