---

- include_tasks: variables.yml

- include_tasks: assertions.yml

- include_tasks: "{{ ansible_os_family }}/install.yml"

- include_tasks: easy-rsa.yml

#- include_tasks: clients.yml

- include_tasks: configure.yml

- name: Upload server keys
  unarchive:
    src: "{{ export_server_file_name }}"
    dest: "{{ openvpn_keydir }}"
    mode: 0600
    owner: root
    group: root

- include_tasks: "{{ ansible_os_family }}/setup-bridge.yml"

- include: firewall.yml
  when: openvpn_route_traffic | bool

- include_tasks: service.yml
